// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTransfers() {
  return window['go']['main']['App']['ClearTransfers']();
}

export function Delete(arg1, arg2) {
  return window['go']['main']['App']['Delete'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function MkDir(arg1, arg2) {
  return window['go']['main']['App']['MkDir'](arg1, arg2);
}

export function PromptDownload(arg1, arg2) {
  return window['go']['main']['App']['PromptDownload'](arg1, arg2);
}

export function PromptUploadDirectory(arg1, arg2) {
  return window['go']['main']['App']['PromptUploadDirectory'](arg1, arg2);
}

export function PromptUploadFiles(arg1, arg2) {
  return window['go']['main']['App']['PromptUploadFiles'](arg1, arg2);
}

export function QueueTransfer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['QueueTransfer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Rename(arg1, arg2, arg3) {
  return window['go']['main']['App']['Rename'](arg1, arg2, arg3);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function TransferItems(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TransferItems'](arg1, arg2, arg3, arg4);
}
