// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {transfer} from '../models';
import {explorer} from '../models';
import {main} from '../models';

export function ClearTransfers():Promise<void>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DisconnectConnection(arg1:string):Promise<void>;

export function GetConnections():Promise<Array<config.ConnectionConfig>>;

export function GetTransfers():Promise<Array<transfer.Transfer>>;

export function GetVersion():Promise<string>;

export function ListDir(arg1:string,arg2:string):Promise<Array<explorer.FileEntry>>;

export function MkDir(arg1:string,arg2:string):Promise<void>;

export function PromptDownload(arg1:string,arg2:string):Promise<void>;

export function PromptUploadDirectory(arg1:string,arg2:string):Promise<void>;

export function PromptUploadFiles(arg1:string,arg2:string):Promise<void>;

export function QueueTransfer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:boolean,arg9:number):Promise<void>;

export function Rename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderConnections(arg1:Array<string>):Promise<void>;

export function SaveConnection(arg1:config.ConnectionConfig,arg2:string):Promise<void>;

export function TransferItems(arg1:string,arg2:string,arg3:string,arg4:Array<main.TransferItem>,arg5:boolean,arg6:number):Promise<void>;
